### ISSUE TITLE
Empty report file results in failed report generation

### ISSUE THREAD

**Issue by calebmfreed** [jenkinsci/cucumber-reports-plugin#33]
I'm running tests in parallel using Parallel Cucumber, but I'm finding that if I skip a certain feature, it will still create a report file with an empty report. This plugin then reports it as "not having any features", and then fails to generate a report at all. It would be really nice if the plugin could ignore empty files or files without features and still generate the report.

I've included a snippet of the error that's thrown when "report5.json" has a size of 0.

```
java.lang.IllegalArgumentException: File '{removed}.../builds/388/cucumber-html-reports/ruby-cucumber/reports/report5.json' does not contan features!
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:37)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:48)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:133)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

**Comment by damianszczepanik** [comment]
What is the sense of generating report from empty json?

**Comment by calebmfreed** [comment]
Having 10 report files means if one is empty there's still plenty to generate reports from, and the empty one can be ignored and no report generated for it.

**Comment by damianszczepanik** [comment]
Makes sense

**Comment by damianszczepanik** [comment]
By empty json I should mean empty file or empty array of the features like
`
    []
`

Empty file could be resulted as error which should not be treated as normal correct result and empty array is currently improved in  #366

**Comment by damianszczepanik** [comment]
@calebmfreed can you precise if you have empty file or empty array of the feature? Can you attach JSON file

**Comment by calebmfreed** [comment]
I'll try to create an example and send it over.

**Comment by damianszczepanik** [comment]
Fixed, should work with next release

**Comment by damianszczepanik** [comment]
Show me JSON file

**Comment by FastDev88** [comment]
@damianszczepanik its an empty file with "[ ]"....

**Comment by damianszczepanik** [comment]
That's because of that
https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/ReportParser.java#L67

**Comment by dogloblin** [comment]
I am still having something similar with 4.3.0 version of the plugin. The empty json file might've been skipped, but the combined report is not generated for the rest of the files, which do have data in them. I.e. the exception from the command line in Jenkins: 

cucumber-reports/153.json' is not proper Cucumber-JVM report
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.InputStreamReader@789d7ba9; line: 1, column: 0]
    at com.fasterxml.jackson.databind.JsonMappingException.from (JsonMappingException.java:261)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading (ObjectMapper.java:3829)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose (ObjectMapper.java:3774)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue (ObjectMapper.java:2878)
    at net.masterthought.cucumber.ReportParser.parseForFeature (ReportParser.java:77)
    at net.masterthought.cucumber.ReportParser.parseJsonFiles (ReportParser.java:55)
    at net.masterthought.cucumber.ReportBuilder.generateReports (ReportBuilder.java:56)
    at net.masterthought.cucumber.CucumberReportGeneratorMojo.execute (CucumberReportGeneratorMojo.java:117)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

cucumber-reports/153.json' does not contain features
